name: duandemo
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4  

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.0.6
  intl: ^0.18.1  
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  speech_to_text: ^7.0.0
  flutter_tts: ^3.8.0  
  google_generative_ai: ^0.4.6
  image_picker: ^1.1.2
  file_picker: ^9.0.0
  universal_html: ^2.2.4
  html: ^0.15.0
  audioplayers: ^6.3.0
  flutter_lints: ^4.0.0
  fl_chart: ^0.66.0

  # Từ chức năng Flashcard thêm vào:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  uuid: ^4.3.3
  google_fonts: ^6.2.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8  # cập nhật version cao hơn từ flashcard
  hive_generator: ^2.0.1  # thêm để hỗ trợ Hive adapter code gen

flutter:
  assets:
    - assets/logo.png

  uses-material-design: true

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
