name: duandemo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.0.6
  intl: ^0.18.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  speech_to_text: ^7.0.0
  flutter_tts: ^3.6.3
  google_generative_ai: ^0.4.6
  image_picker: ^1.1.2
  file_picker: ^9.0.0
  universal_html: ^2.2.4
  html: ^0.15.0
  flutter_lints: ^4.0.0
  audioplayers: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
